PREFIX dblp: <https://dblp.org/rdf/schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?publ ?title ?doi ?year ?stream ?venue ?pers ?name ?homepage ?ord ?n WHERE {
  ?publ dblp:publishedInStream ?stream .
  ?publ dblp:yearOfPublication ?year .
  ?publ dblp:numberOfCreators ?n .
  ?publ dblp:title ?title .
  ?publ dblp:hasSignature ?sig .
  ?sig rdf:type dblp:AuthorSignature .
  ?sig dblp:signatureOrdinal ?ord .
  ?sig dblp:signatureCreator ?pers .
  ?publ dblp:doi ?doi .
  ?sig dblp:signatureDblpName ?name .
  OPTIONAL { ?stream dblp:streamTitle ?venue . }
  OPTIONAL { ?pers dblp:homepage ?homepage . }
}